version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollbar
    versions:
    - 2.19.4
    - 2.20.0
  - dependency-name: helmet
    versions:
    - 4.3.1
  - dependency-name: supertest
    versions:
    - 6.0.1
  - dependency-name: m
    versions:
    - 1.5.6
