# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8.0
      - image: mongo:3.4.4

    working_directory: ~/SchoolBusTracker_WebServices

    steps:
      - run:
          name: "Checking Versions"
          command:
            node --version
            npm --version
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          # run tests!
      - run: yarn test
      - store_test_results:
          path: test-results
